#!/bin/bash
#data1=$(rmnet_data1)
#data2=$(rmnet_data2)

ip1=$(ip -4 addr show rmnet_data2 | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | awk '{print $1}')
ip2=$(ip -4 addr show rmnet_data1 | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | awk '{print $1}')

dialog --backtitle "                         Ripunk@E99" --title  \
       "Open Clash" --inputbox \
"Your IP: $ip1 $ip2\n_________________________________________\nMenu Tunnel :\n_________________________________________\n|1. Trojan Single Akun                  |\n|2. Trojan LB                           |\n|3. Vmess                               |\n_________________________________________\nMenu Config :\n_________________________________________\n|4. Backup Config                       |\n|5. Restore Config                      |\n_________________________________________\nStart Tunnels :\n_________________________________________\n|6. Start Clash                         |\n|7. Stop Clash                          |\n_________________________________________\n                               By :Ripunk " 25 45 2>pilih
pil=$(<pilih)

case $pil in
1)
dialog --inputbox "Profile :" 10 45 2>prof
namet1=$(<prof)
            dialog --inputbox "SNI :" 10 45 2>snit1.txt
            snt1=$(<snit1.txt)
            dialog --inputbox "Import URL :" 10 45 2>trojan1.txt
            url1=$(<trojan1.txt)
host1=$(grep trojan:// trojan1.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $2}'|awk -F ":" '{print $1}'|awk "NR==1")
#host=$(ping $host -w1 -c1|awk "NR==1"|awk -F '(' '{print $2}'|awk -F ')' '{print $1}')
port1=$(grep trojan:// trojan1.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $2}'|awk -F ":" '{print $2}'|awk -F "/" '{print $1}'|awk "NR==1")
#sni=$(grep sni= sni1.txt|awk -F "=" '{print $2}')
pass1=$(grep trojan:// trojan1.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $1}'|awk "NR==1")
echo """port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 9898
bind-address: '*'
mode: rule
allow-lan: true
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
unified-delay: true
ipv6: false
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.0/8
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
  fallback:
    - https://dns.google/dns-query  
proxies:
  - {name: $namet1, server: $host1, port: $port1, udp: true, type: trojan, password: $pass1, sni: $snt1, skip-cert-verify: true}
#  - {name: Nh, server: wanrancomp.duckdns.org, port: 443, type: vmess, uuid: ace296d8-c78f-4a57-99d8-501cee4198b3, sni: v24.tiktokcdn.com, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, udp: true, network: ws, ws-path: /76ddd844e/, ws-headers: {Host: v24.tiktokcdn.com}}
proxy-groups:
  - name: AKUN
    type: load-balance
    url: 'http://www.gstatic.com/generate_204'
    interval: 250
    strategy: consistent-hashing
    proxies: 
      - $namet1
#      - Nh
rules:
  - MATCH,AKUN """ > $HOME/.config/clash/single.yaml
echo """
Akun Trojan
Profile : $namet1
Server  : $host1
port    : $port1
Password: $pass1
Sni     : $snt1
""" >single.txt
akun=$(cat single.txt)
display_result () {
 dialog --title "Info Account" \
        --no-collapse \
        --msgbox "$akun" 0 0
}

result=$(cat akunt.txt)
display_result
rm single.txt 2>&1
rm prof 2>&1
rm snit1.txt 2>&1
rm trojan1.txt 2>&1
sleep 2
mv $HOME/.config/clash/config.yaml $HOME/.config/clash/configbackup.yaml
mv $HOME/.config/clash/single.yaml $HOME/.config/clash/config.yaml
clash -t -d $HOME/.config/clash -f $HOME/.config/clash/config.yaml >HOME/.config/clash/run.logs
screen -dmS v2 clash
for i in $(seq 1 100)
do
    sleep 0.1 
    echo $i
done | whiptail --title 'Start Clash' --gauge 'Connecting...' 6 60 0
status=$(cat $HOME/.config/clash/run.logs)
display_result () {
 dialog --title "Status Tunnels" \
        --no-collapse \
        --msgbox "$status" 0 0
}
status=$(cat $HOME/.config/clash/run.logs)
display_result
xdg-open "http://127.0.0.1:9090/ui/#/proxies" & exit
;;

2)
 dialog --inputbox "Profile :" 10 45 2>namet2
            nmt2=$(<namet2)
            dialog --inputbox "SNI :" 10 45 2>snit2.txt
            snt2=$(<snit2.txt)
            dialog --inputbox "Import URL :" 10 45 2>trojan2.txt
            url2=$(<trojan2.txt)
host2=$(grep trojan:// trojan2.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $2}'|awk -F ":" '{print $1}'|awk "NR==1")
#host=$(ping $host -w1 -c1|awk "NR==1"|awk -F '(' '{print $2}'|awk -F ')' '{print $1}')
port2=$(grep trojan:// trojan2.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $2}'|awk -F ":" '{print $2}'|awk -F "/" '{print $1}'|awk "NR==1")
#sni=$(grep sni= sni1.txt|awk -F "=" '{print $2}')
pass2=$(grep trojan:// trojan2.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $1}'|awk "NR==1")
echo """proxies:
- name: "$nmt2"
  type: trojan
  server: $host2
  port: $port2
  password: $pass2
  udp: true
  sni: $snt2
  skip-cert-verify: true """ > .config/clash/Game.yaml
sleep 2
dialog --inputbox "Profile :" 10 45 2>namet3
            nmt3=$(<namet3)
            dialog --inputbox "SNI :" 10 45 2>snit3.txt
            snt3=$(<snit3.txt)
            dialog --inputbox "Import URL :" 10 45 2>trojan3.txt
            url3=$(<trojan3.txt)
host3=$(grep trojan:// trojan3.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $2}'|awk -F ":" '{print $1}'|awk "NR==1")
#host=$(ping $host -w1 -c1|awk "NR==1"|awk -F '(' '{print $2}'|awk -F ')' '{print $1}')
port3=$(grep trojan:// trojan3.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $2}'|awk -F ":" '{print $2}'|awk -F "/" '{print $1}'|awk "NR==1")
#sni=$(grep sni= sni1.txt|awk -F "=" '{print $2}')
pass3=$(grep trojan:// trojan3.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $1}'|awk "NR==1")
echo """proxies:
- name: "$nmt3"
  type: trojan
  server: $host3
  port: $port3
  password: $pass3
  udp: true
  sni: $snt3
  skip-cert-verify: true """ > .config/clash/Sosmed.yaml
sleep 2
dialog --inputbox "Profile :" 10 45 2>namet4
            nmt4=$(<namet4)
            dialog --inputbox "SNI :" 10 45 2>snit4.txt
            snt4=$(<snit4.txt)
            dialog --inputbox "Import URL :" 10 45 2>trojan4.txt
            url4=$(<trojan4.txt)
host4=$(grep trojan:// trojan4.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $2}'|awk -F ":" '{print $1}'|awk "NR==1")
#host=$(ping $host -w1 -c1|awk "NR==1"|awk -F '(' '{print >
port4=$(grep trojan:// trojan4.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $2}'|awk -F ":" '{print $2}'|awk -F "/" '{print $1}'|awk "NR==1")
#sni=$(grep sni= sni1.txt|awk -F "=" '{print $2}')
pass4=$(grep trojan:// trojan4.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $1}'|awk "NR==1")
echo """proxies:
- name: "$nmt4"
  type: trojan
  server: $host4
  port: $port4
  password: $pass4
  udp: true
  sni: $snt4
  skip-cert-verify: true """ > .config/clash/Youtube.yaml
sleep 2
dialog --inputbox "Profile :" 10 45 2>namet5
            nmt5=$(<namet5)
            dialog --inputbox "SNI :" 10 45 2>snit5.txt
            snt5=$(<snit5.txt)
            dialog --inputbox "Import URL :" 10 45 2>trojan5.txt
            url5=$(<trojan5.txt)
host5=$(grep trojan:// trojan5.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $2}'|awk -F ":" '{print $1}'|awk "NR==1")
port5=$(grep trojan:// trojan5.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $2}'|awk -F ":" '{print $2}'|awk -F "/" '{print $1}'|awk "NR==1")
pass5=$(grep trojan:// trojan5.txt|awk -F "://" '{print $2}'|awk -F "@" '{print $1}'|awk "NR==1")
echo """proxies:
- name: "$nmt5"
  type: trojan
  server: $host5
  port: $port5
  password: $pass5
  udp: true
  sni: $snt5
  skip-cert-verify: true """ > .config/clash/Browser.yaml
rm namet2 2>&1
rm snit2.txt 2>&1
rm trojan2.txt 2>&1
rm namet3 2>&1
rm snit3.txt 2>&1
rm trojan3.txt 2>&1
rm namet4 2>&1
rm snit4.txt 2>&1
rm trojan4.txt 2>&1
rm namet5 2>&1
rm snit5.txt 2>&1
rm trojan5.txt 2>&1
echo """
akun trojan 1
Profile       : $nmt2
Host          : $host2
Port           : $port2
password : $pass2
sni              : $snt2
_________________________________
akun trojan 2
Profile       : $nmt3
Host          : $host3
Port           : $port3
password : $pass3
sni              : $snt3
__________________________________
akun trojan 3
Profile       : $nmt4
Host          : $host4
Port           : $port4
password : $pass4
sni              : $snt4
___________________________________
akun trojan 4
Profile       : $nmt5
Host          : $host5
Port           : $port5
password : $pass5
sni              : $snt5
___________________________________
"""> akunt.txt
display_result () {
 dialog --title "Info Account" \
        --no-collapse \
        --msgbox "$result" 0 0
}

result=$(cat akunt.txt)
display_result
rm akunt.txt 2>&1 
clear
#mv $HOME/.config/clash/config.yaml $HOME/.config/clash/configbackup.yaml
cp $HOME/.config/clash/lb/config.yaml $HOME/.config/clash/config.yaml
clash -t -d $HOME/.config/clash -f $HOME/.config/clash/config.yaml
screen -dmS v2 clash
for i in $(seq 1 100)
do
    sleep 0.1 
    echo $i
done | whiptail --title 'Start Clash' --gauge 'Connecting...' 6 60 0
status=$(cat $HOME/.config/clash/run/run.logs)
display_result () {
 dialog --title "Status Tunnels" \
        --no-collapse \
        --msgbox "$status" 0 0
}
status=$(cat $HOME/.config/clash/run/run.logs)
display_result
xdg-open "http://127.0.0.1:9090/ui/#/proxies" & exit
;;

3)
dialog --inputbox "Profile :" 10 45 2>namev
            nmv=$(<namev)
            dialog --inputbox "BUG : " 10 45 2>bug.txt
            bug=$(<bug.txt)
            dialog --inputbox "Iport URL" 10 45 2>vmess.txt
            urlv=$(<vmess.txt)
            sleep 2
mkdir -p v2ray;juuid=1;n2
portv=$(grep vmess: vmess.txt 2>/dev/null|awk -F "//" '{print $2}'|base64 -d 2>/dev/null|sed ':a;N;$!ba;s/\n  //g'|awk -F '"port' '{print $2}'|grep :|sed ':a;N;$!ba;s/\n/ /g'|awk -F ',' '{print $1}'|sed -e 's/://g' -e 's/ //g' -e 's/"//g')
  if [ ! -f $portv ]; then
 while [ $juuid -lt 17 ]; do
uuid=$(grep vmess: vmess.txt 2>/dev/null|awk -F "//" '{print $2}'|base64 -d 2>/dev/null|sed ':a;N;$!ba;s/\n  //g'|awk -F 'id' '{print $"'$n'"}'|grep :|sed ':a;N;$!ba;s/\n/ /g'|awk -F ',' '{print $1}'|sed -e 's/://g' -e 's/ //g' -e 's/"//g')
juuid=$(echo $uuid|wc -c);((n++))
 done
hostv=$(grep vmess: vmess.txt 2>/dev/null|awk -F "//" '{print $2}'|base64 -d 2>/dev/null|sed ':a;N;$!ba;s/\n  //g'|awk -F '"add' '{print $2}'|grep :|sed ':a;N;$!ba;s/\n/ /g'|awk -F ',' '{print $1}'|sed -e 's/://g' -e 's/ //g' -e 's/"//g')
aid=$(grep vmess: vmess.txt 2>/dev/null|awk -F "//" '{print $2}'|base64 -d 2>/dev/null|sed ':a;N;$!ba;s/\n  //g'|awk -F '"aid' '{print $2}'|grep :|sed ':a;N;$!ba;s/\n/ /g'|awk -F ',' '{print $1}'|sed -e 's/://g' -e 's/ //g' -e 's/"//g')
net=$(grep vmess: vmess.txt 2>/dev/null|awk -F "//" '{print $2}'|base64 -d 2>/dev/null|sed ':a;N;$!ba;s/\n  //g'|awk -F '"net' '{print $2}'|grep :|sed ':a;N;$!ba;s/\n/ /g'|awk -F ',' '{print $1}'|sed -e 's/://g' -e 's/ //g' -e 's/"//g')
path=$(grep vmess: vmess.txt 2>/dev/null|awk -F "//" '{print $2}'|base64 -d 2>/dev/null|sed ':a;N;$!ba;s/\n  //g'|awk -F '"path' '{print $2}'|grep :|sed ':a;N;$!ba;s/\n/ /g'|awk -F ',' '{print $1}'|sed -e 's/://g' -e 's/ //g' -e 's/"//g')
path=$(echo $path|sed 's/\\u003d/=/g'|sed 's/\\u0026/\&/g')
tls=$(grep vmess: vmess.txt 2>/dev/null|awk -F "//" '{print $2}'|base64 -d 2>/dev/null|sed ':a;N;$!ba;s/\n/ /g'|awk -F 'tls":' '{print $2}'|awk -F ',' '{print $1}'|sed -e 's/://g' -e 's/ //g' -e 's/"//g' -e 's/}//g')
if [ -f $tls ]; then
tls=$(grep vmess: vmess.txt 2>/dev/null|awk -F "//" '{print $2}'|base64 -d 2>/dev/null|grep tls|sed -e 's/:/=/g' -e 's/ //g' -e 's/"//g' -e 's/}//g'|awk -F "=" '{print $1}')
 if [ ! -f $tls ]; then
  if [ $tls != "tls" ]; then
  tls=""
  fi
 fi
fi
   fi

echo """
proxies :
- name: $nmv
  server: $hostv
  port: $portv
  type: vmess
  uuid: $uuid
  sni: $bug
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  udp: true
  network: ws
  ws-path: $path
  ws-headers: {Host: $bug}}""" > .config/clash/Sosmed.yaml
echo """
Profile : $nmv
Host    : $hostv
Port    : $portv
uuid    : $uuid
path    : $path
sni     : $bug
"""> akun.txt
display_result () {
 dialog --title "Info Account" \
        --no-collapse \
        --msgbox "$result" 0 0
}

result=$(cat akun.txt)
display_result

mv config.yaml /sdcard/.config/clash/ 2>&1
sleep 2
rm bug.txt 2>&1
rm vmess.txt 2>&1
rm akun.txt 2>&1
bash openclash
;;
4)
mkdir backupclash #2>&1
cp $HOME/.config/clash/*.yaml $HOME/backupclash #2>&1
cp -R backupclash /sdcard #$2>&1
#a=$?
#$if [ $a = 0 ]; then
#cp -R /backupclash/*.yaml /sdcard/backupclash
rm -r -f backupclash
#fi
for i in $(seq 1 100)
do
   sleep 0.1 
    echo $i
done | whiptail --title 'Backup Config' --gauge 'Please wait...' 6 60 0
#stat=$(Config Sukses Di Backup, Config Berada Di Directory Sdcard/backupclash)
display_result () {
 dialog --title "Sukses Backup" \
        --no-collapse \
        --msgbox "File berada di sdcard/backupclash" 0 0
}
#stat=$(Config Sukses Di Backup,Config Berada Di Directory Sdcard/backupclash)
display_result
;;
5)
dialog --inputbox "Masukan Directory anda menyimpan Config..\nContoh :\nsdcard/Downloads/config.yaml:" 10 45 2>import
imp=$(<import)
cp -r -f /$imp $HOME/.config/clash/config.yaml 2>&1
display_result () {
 dialog --title "Sukses Restore" \
        --no-collapse \
        --msgbox "Restore Sukses" 0 0
}
#stat=$(Config Sukses Di Backup,Config Berada Di Directory Sdcard/backupclash)
display_result
rm import 2>&1
;;
6)
 #       cp $HOME/.config/clash/a/config.yaml $HOME/.config/clash/ 2>&1
        clash -t -d $HOME/.config/clash -f $HOME/.config/clash/config.yaml > $HOME/.config/clash/run.logs
clear
screen -dmS v2 clash &
for i in $(seq 1 100)
do
   sleep 0.1 
    echo $i
done | whiptail --title 'Start Clash' --gauge 'Connecting...' 6 60 0
status=$(cat $HOME/.config/clash/run.logs)
display_result () {
 dialog --title "Status Tunnels" \
        --no-collapse \
        --msgbox "$status" 0 0
}
status=$(cat $HOME/.config/clash/run.logs)
display_result
xdg-open "http://127.0.0.1:9090/ui/#/proxies" & exit
;;
7)
pidof clash >pid
PID=$(<pid)
kill -9 $PID
rm pid 2>&1
;;
esac
rm pilih 2>&1